name: 02 - Manually create a shared environment

on:
  workflow_dispatch:
    inputs:
      environmentName:
        description: 'The name of the environment to create'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

jobs:
  deploy-network-stack:
    runs-on: ubuntu-20.04
    name: Deploy the network stack
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: NPM install
        working-directory: cdk
        run: npm install

      - name: Deploy network stack
        working-directory: cdk
        run: npm run network:deploy -- -c environmentName=${{ github.event.inputs.environmentName }}
