name: 05 - Update the Todo-App in staging

on:
  workflow_dispatch:
    inputs:
      docker-image-tag:
        description: "The docker image to deploy"
        required: true

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

jobs:
  deploy-app:
    runs-on: ubuntu-20.04
    name: Deploy Todo App
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: NPM install
        working-directory: cdk
        run: npm install

      - name: Create or update service stack
        if: github.ref == 'refs/heads/main'
        working-directory: cdk
        run: |
          npm run service:deploy -- -c environmentName=staging -c springProfile=staging -c applicationName=todo-app -c dockerRepositoryName=todo-app -c dockerImageTag=${{github.event.inputs.docker-image-tag}}
